# Generated by Django 4.1.7 on 2023-04-17 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardealer', '0002_make_alter_car_make'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='car',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='make',
            table='make',
        ),
        migrations.AlterModelTable(
            name='sale',
            table='sale',
        ),
    ]
