version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: cardealer
      POSTGRES_USER: ayttekao
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1;' | psql -U ayttekao -d cardealer" ]
      interval: 3s
      timeout: 5s
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - db

  nginx:
    image: nginx:1.21.3
    restart: unless-stopped
    volumes:
      - ./lab_03/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    networks:
      - db
    depends_on:
      django:
        condition: service_healthy

  django:
    build: .
    command: sh -c "
      python lab_03/carProject/manage.py migrate &&
      python lab_03/carProject/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8081:8000"
    networks:
      - db
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://0.0.0.0:8000/healthcheck/"]
      interval: 3s
      timeout: 5s
    restart: unless-stopped

networks:
  db:
    driver: bridge